In [ ]:
import math
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from tensorflow.keras.layers import DenseFeatures
from tensorflow.feature_column import categorical_column_with_hash_bucket, numeric_column, embedding_column

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_excel('/content/drive/MyDrive/DataSet Makanan Indo Bersih.xls')
data2 = data

In [ ]:
data.head()

No.   Kode    Nama Bahan Makanan  Energi(Kal)  Protein(g)  Lemak(g)  \
0    1  AP001                  Nasi        173.9         3.0       0.3   
1    2  AP002              Nasi tim        117.2         2.4       0.4   
2    3  AP003           Tapai beras         99.1         1.7       0.3   
3    4  AP004  Tepung beras. mentah        352.5         7.0       0.5   
4    5  AP005      Nasi beras merah        144.8         2.8       0.4   

   Karbohidrat(g)  
0            39.8  
1            26.0  
2            22.4  
3            80.0  
4            32.5

In [ ]:
data.tail()

No.  Kode                              Nama Bahan Makanan  Energi(Kal)  \
2043  2044  9316                                Stroberi. mentah        36.10   
2044  2045  9059                                   Sukun. mentah       114.83   
2045  2046  9195      Zaitun. asinan. kalengan atau botol. hijau       157.36   
2046  2047  9194  Zaitun. matang. kalengan (jumbo-super kolosal)        88.15   
2047  2048  9193   Zaitun. matang. kalengan (kecil-ekstra besar)       124.52   

      Protein(g)  Lemak(g)  Karbohidrat(g)  
2043        0.67      0.30            7.68  
2044        1.07      0.23           27.12  
2045        1.03     15.32            3.84  
2046        0.97      6.87            5.61  
2047        0.84     10.68            6.26

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2048 entries, 0 to 2047
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   No.                 2048 non-null   int64  
 1   Kode                2048 non-null   object 
 2   Nama Bahan Makanan  2048 non-null   object 
 3   Energi(Kal)         2048 non-null   float64
 4   Protein(g)          2048 non-null   float64
 5   Lemak(g)            2048 non-null   float64
 6   Karbohidrat(g)      2048 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 112.1+ KB


In [ ]:
data.shape

(2048, 7)

In [ ]:
data.isna().sum()

No.                   0
Kode                  0
Nama Bahan Makanan    0
Energi(Kal)           0
Protein(g)            0
Lemak(g)              0
Karbohidrat(g)        0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2048 entries, 0 to 2047
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   No.                 2048 non-null   int64  
 1   Kode                2048 non-null   object 
 2   Nama Bahan Makanan  2048 non-null   object 
 3   Energi(Kal)         2048 non-null   float64
 4   Protein(g)          2048 non-null   float64
 5   Lemak(g)            2048 non-null   float64
 6   Karbohidrat(g)      2048 non-null   float64
dtypes: float64(4), int64(1), object(2)
memory usage: 112.1+ KB


In [ ]:
features = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Energi(Kal)'])

In [ ]:
features

Protein(g)  Lemak(g)  Karbohidrat(g)
0           3.00      0.30           39.80
1           2.40      0.40           26.00
2           1.70      0.30           22.40
3           7.00      0.50           80.00
4           2.80      0.40           32.50
...          ...       ...             ...
2043        0.67      0.30            7.68
2044        1.07      0.23           27.12
2045        1.03     15.32            3.84
2046        0.97      6.87            5.61
2047        0.84     10.68            6.26

[2048 rows x 3 columns]

In [ ]:
targets = data.drop(columns= ['No.','Kode', 'Nama Bahan Makanan', 'Protein(g)', 'Lemak(g)', 'Karbohidrat(g)'])

In [ ]:
targets

Energi(Kal)
0          173.90
1          117.20
2           99.10
3          352.50
4          144.80
...           ...
2043        36.10
2044       114.83
2045       157.36
2046        88.15
2047       124.52

[2048 rows x 1 columns]

In [ ]:
np.unique(targets)

array([  8.2,  10.5,  11.7, ..., 898.1, 899.1, 900. ])

In [ ]:
len(np.unique(targets))

1812

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation = 'relu', input_shape=(3,)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'linear')
])


In [ ]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss='mse')

In [ ]:
model.fit(features, targets, epochs = 50, validation_split = 0.2, verbose = 2)

Epoch 1/50
52/52 - 8s - loss: 74423.1172 - val_loss: 30273.5605 - 8s/epoch - 161ms/step
Epoch 2/50
52/52 - 0s - loss: 55898.3594 - val_loss: 13338.2451 - 244ms/epoch - 5ms/step
Epoch 3/50
52/52 - 0s - loss: 18864.9121 - val_loss: 3117.4768 - 200ms/epoch - 4ms/step
Epoch 4/50
52/52 - 0s - loss: 4765.0874 - val_loss: 2060.1101 - 209ms/epoch - 4ms/step
Epoch 5/50
52/52 - 0s - loss: 2462.6863 - val_loss: 1019.6094 - 209ms/epoch - 4ms/step
Epoch 6/50
52/52 - 0s - loss: 1100.4413 - val_loss: 432.8375 - 203ms/epoch - 4ms/step
Epoch 7/50
52/52 - 0s - loss: 416.0901 - val_loss: 185.3812 - 250ms/epoch - 5ms/step
Epoch 8/50
52/52 - 0s - loss: 154.1613 - val_loss: 68.1203 - 197ms/epoch - 4ms/step
Epoch 9/50
52/52 - 0s - loss: 70.5365 - val_loss: 35.0534 - 212ms/epoch - 4ms/step
Epoch 10/50
52/52 - 0s - loss: 39.5707 - val_loss: 18.5991 - 202ms/epoch - 4ms/step
Epoch 11/50
52/52 - 0s - loss: 24.6709 - val_loss: 14.8386 - 241ms/epoch - 5ms/step
Epoch 12/50
52/52 - 0s - loss: 15.9041 - val_loss: 8.73

In [ ]:
model.predict(features.head(2))

1/1 [==============================] - 0s 97ms/step


array([[173.97623 ],
       [117.315186]], dtype=float32)

In [ ]:
protein_features = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Protein(g)'])

In [ ]:
protein_targets = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Energi(Kal)', 'Lemak(g)', 'Karbohidrat(g)'])

In [ ]:
model_protein = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation = 'relu', input_shape=(3,)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'linear')
])


In [ ]:
model_protein.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss='mse')

In [ ]:
model_protein.fit(protein_features, protein_targets, epochs = 50, validation_split = 0.2, verbose = 2)

Epoch 1/50
52/52 - 2s - loss: 216.6541 - val_loss: 25.1865 - 2s/epoch - 34ms/step
Epoch 2/50
52/52 - 0s - loss: 100.1889 - val_loss: 15.9831 - 251ms/epoch - 5ms/step
Epoch 3/50
52/52 - 0s - loss: 96.1324 - val_loss: 14.6527 - 248ms/epoch - 5ms/step
Epoch 4/50
52/52 - 0s - loss: 90.9249 - val_loss: 13.6879 - 209ms/epoch - 4ms/step
Epoch 5/50
52/52 - 0s - loss: 87.6030 - val_loss: 11.4534 - 202ms/epoch - 4ms/step
Epoch 6/50
52/52 - 0s - loss: 83.9338 - val_loss: 10.1574 - 245ms/epoch - 5ms/step
Epoch 7/50
52/52 - 0s - loss: 78.5752 - val_loss: 10.5490 - 202ms/epoch - 4ms/step
Epoch 8/50
52/52 - 0s - loss: 73.8355 - val_loss: 9.8466 - 202ms/epoch - 4ms/step
Epoch 9/50
52/52 - 0s - loss: 66.9651 - val_loss: 8.1357 - 194ms/epoch - 4ms/step
Epoch 10/50
52/52 - 0s - loss: 58.4673 - val_loss: 6.7482 - 198ms/epoch - 4ms/step
Epoch 11/50
52/52 - 0s - loss: 50.7591 - val_loss: 7.5463 - 204ms/epoch - 4ms/step
Epoch 12/50
52/52 - 0s - loss: 40.0825 - val_loss: 5.7114 - 197ms/epoch - 4ms/step
Epoch 

In [ ]:
model_protein.predict(protein_features.head(1))

1/1 [==============================] - 0s 105ms/step


array([[2.9613469]], dtype=float32)

In [ ]:
lemak_features = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Lemak(g)'])

In [ ]:
lemak_targets = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Energi(Kal)', 'Protein(g)', 'Karbohidrat(g)'])

In [ ]:
model_lemak = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation = 'relu', input_shape=(3,)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'linear')
])


In [ ]:
model_lemak.compile(optimizer=tf.keras.optimizers.Adam(0.0001),
              loss='mse')

In [ ]:
model_lemak.fit(lemak_features, lemak_targets, epochs = 50, validation_split = 0.2, verbose = 2)

Epoch 1/50
52/52 - 2s - loss: 100.5658 - val_loss: 14.3088 - 2s/epoch - 38ms/step
Epoch 2/50
52/52 - 0s - loss: 29.1363 - val_loss: 3.5227 - 204ms/epoch - 4ms/step
Epoch 3/50
52/52 - 0s - loss: 13.0499 - val_loss: 1.3363 - 197ms/epoch - 4ms/step
Epoch 4/50
52/52 - 0s - loss: 4.7547 - val_loss: 0.2839 - 194ms/epoch - 4ms/step
Epoch 5/50
52/52 - 0s - loss: 0.9106 - val_loss: 0.0588 - 199ms/epoch - 4ms/step
Epoch 6/50
52/52 - 0s - loss: 0.1934 - val_loss: 0.0355 - 241ms/epoch - 5ms/step
Epoch 7/50
52/52 - 0s - loss: 0.0429 - val_loss: 0.0256 - 241ms/epoch - 5ms/step
Epoch 8/50
52/52 - 0s - loss: 0.0328 - val_loss: 0.0162 - 241ms/epoch - 5ms/step
Epoch 9/50
52/52 - 0s - loss: 0.0264 - val_loss: 0.0149 - 207ms/epoch - 4ms/step
Epoch 10/50
52/52 - 0s - loss: 0.0205 - val_loss: 0.0146 - 201ms/epoch - 4ms/step
Epoch 11/50
52/52 - 0s - loss: 0.0180 - val_loss: 0.0100 - 209ms/epoch - 4ms/step
Epoch 12/50
52/52 - 0s - loss: 0.0147 - val_loss: 0.0084 - 205ms/epoch - 4ms/step
Epoch 13/50
52/52 - 0s

In [ ]:
model_lemak.predict(lemak_features.head(1))

1/1 [==============================] - 0s 70ms/step


array([[0.31384808]], dtype=float32)

In [ ]:
karbohidrat_features = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Karbohidrat(g)'])

In [ ]:
karbohidrat_targets = data.drop(columns = ['No.','Kode', 'Nama Bahan Makanan', 'Energi(Kal)', 'Protein(g)', 'Lemak(g)'])

In [ ]:
model_karbohidrat = tf.keras.models.Sequential([
    tf.keras.layers.Dense(256, activation = 'relu', input_shape=(3,)),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'linear')
])

In [ ]:
model_karbohidrat.compile(optimizer=tf.keras.optimizers.Adam(0.0001), loss='mse')

In [ ]:
model_karbohidrat.fit(karbohidrat_features, karbohidrat_targets, epochs = 50, validation_split = 0.2, verbose = 2)

Epoch 1/50
52/52 - 2s - loss: 443.3083 - val_loss: 327.0764 - 2s/epoch - 35ms/step
Epoch 2/50
52/52 - 0s - loss: 361.6698 - val_loss: 298.8955 - 245ms/epoch - 5ms/step
Epoch 3/50
52/52 - 0s - loss: 337.5822 - val_loss: 296.3202 - 201ms/epoch - 4ms/step
Epoch 4/50
52/52 - 0s - loss: 306.2846 - val_loss: 254.1606 - 239ms/epoch - 5ms/step
Epoch 5/50
52/52 - 0s - loss: 268.4158 - val_loss: 236.6593 - 209ms/epoch - 4ms/step
Epoch 6/50
52/52 - 0s - loss: 218.4164 - val_loss: 127.9328 - 238ms/epoch - 5ms/step
Epoch 7/50
52/52 - 0s - loss: 108.6667 - val_loss: 48.5299 - 234ms/epoch - 4ms/step
Epoch 8/50
52/52 - 0s - loss: 37.6886 - val_loss: 19.0133 - 200ms/epoch - 4ms/step
Epoch 9/50
52/52 - 0s - loss: 10.2644 - val_loss: 2.5384 - 279ms/epoch - 5ms/step
Epoch 10/50
52/52 - 0s - loss: 2.2848 - val_loss: 0.2934 - 336ms/epoch - 6ms/step
Epoch 11/50
52/52 - 0s - loss: 0.4379 - val_loss: 0.2053 - 317ms/epoch - 6ms/step
Epoch 12/50
52/52 - 0s - loss: 0.2527 - val_loss: 0.2002 - 314ms/epoch - 6ms/st

In [ ]:
model_karbohidrat.predict(karbohidrat_features.head(1))

1/1 [==============================] - 0s 63ms/step


array([[39.745075]], dtype=float32)

**Recommender**

In [ ]:
import random

def recommend_foods(data, calorie_limit, tolerance=50):
    # Shuffle the dataframe
    data = data.sample(frac=1, random_state=random.randint(0, 1000))

    # Initialize an empty list to hold the recommended foods
    recommended_foods = []

    # Initialize a variable to hold the total calories of the recommended foods
    total_calories = 0

    # Iterate over the rows of the shuffled dataframe
    for index, row in data.iterrows():
        # If adding the current food does not exceed the calorie limit
        if total_calories + row['Energi(Kal)'] <= calorie_limit + tolerance:
            # Add the food and its calorie content to the list of recommended foods
            recommended_foods.append((row['Nama Bahan Makanan'], row['Energi(Kal)']))
            # Add the calories of the current food to the total calories
            total_calories += row['Energi(Kal)']
        # If the total calories is close to the calorie limit, stop adding foods
        if total_calories >= calorie_limit:
            break

    return recommended_foods, total_calories

# Call the function
foods, total_calories = recommend_foods(data, 2000)
for food, calories in foods:
    print(f"Food: {food}, Calories: {np.round(calories, 1)}")
print(f"Total Calories: {np.round(total_calories, 1)}")


Food: Andewi. segar, Calories: 29.4
Food: Makanan Ringan. granola. lembut. tidak dilapisi. keping coklat, Calories: 452.5
Food: Embacang. segar, Calories: 109.0
Food: Alpukat. mentah. semua varietas komersial, Calories: 174.1
Food: Makanan Ringan. pretzel. keras. polos. dibuat dengan tepung yang tidak diperkaya. tidak tawar, Calories: 384.7
Food: Jawawut. mentah, Calories: 363.9
Food: Makanan cepat saji. sandwich ikan. dengan saus tartar dan keju, Calories: 282.4
Food: Jeruk banjar. segar, Calories: 61.4
Food: Pisang ambon. segar, Calories: 108.4
Food: Kapri muda. segar, Calories: 51.0
Total Calories: 2016.8


In [ ]:
import numpy as np
import tensorflow as tf
import random

# Number of items
num_items = len(data)

# Weights and values
weights = data['Lemak(g)'].values  # We use fat as the weight
values = data['Energi(Kal)'].values  # We use calories as the value

# Knapsack capacity
capacity = 30  # This is the total amount of fat we want to minimize

# State: (current weight, item, total value)
state = tf.keras.Input(shape=(3,))

# Q-values: (do nothing, pick item)
q_values = tf.keras.layers.Dense(2)(state)

# Model
model3 = tf.keras.Model(inputs=state, outputs=q_values)

# Loss and optimizer
loss_fn = tf.keras.losses.MeanSquaredError()
optimizer = tf.keras.optimizers.Adam()

# Discount factor
gamma = 0.95

# Epsilon for epsilon-greedy strategy
epsilon = 1.0
epsilon_decay = 0.995

# Training loop
stop_training = False
selected_foods = []  # Initialize an empty list to store selected foods

for episode in range(1000):  # Increase the number of episodes
    # Initial state
    current_weight = 0
    total_value = 0

    for item in range(num_items):
        # Current state
        current_state = np.array([[current_weight, item, total_value]])

        # Compute Q-values
        current_q_values = model3.predict(current_state)

        # Choose action
        if np.random.rand() < epsilon:
            action = np.random.randint(2)
        else:
            action = np.argmax(current_q_values)

        # Update current weight and total value
        if action == 1 and current_weight + weights[item] <= capacity:
            current_weight += weights[item]
            total_value += values[item]

            # Save the selected item if the weight and value constraints are met
            selected_foods.append((data['Nama Bahan Makanan'][item], values[item]))

        # Print the weights and total value per loop
        print(f"Current weight: {current_weight}, Total value: {total_value}")

        # Compute reward
        reward = total_value - current_weight  # Adjust the reward function

        # Next state
        next_state = np.array([[current_weight, item + 1, total_value]])

        # Compute next Q-values
        next_q_values = model3.predict(next_state)

        # Compute target Q-values
        target_q_values = current_q_values
        target_q_values[0, action] = reward + gamma * np.max(next_q_values)

        # Update model
        with tf.GradientTape() as tape:
            q_values = model3(current_state)
            loss = loss_fn(target_q_values, q_values)
        grads = tape.gradient(loss, model3.trainable_weights)
        optimizer.apply_gradients(zip(grads, model3.trainable_weights))

        # Check if the total value exceeds 2000 and break both loops
        if total_value >= 2000:
            print("Total value exceeds 2000. Stopping training.")
            stop_training = True
            break

    # Decrease epsilon
    epsilon *= epsilon_decay

    if stop_training:
        break

# Print the recommended foods
print("Recommended Foods:")
for food, calories in selected_foods:
    print(f"Food: {food}, Calories: {calories}")

print(f"Total Calories: {sum(calories for _, calories in selected_foods)}")


1/1 [==============================] - 0s 49ms/step
Current weight: 0.3, Total value: 173.89999999999998
1/1 [==============================] - 0s 25ms/step
Current weight: 0.3, Total value: 173.89999999999998
1/1 [==============================] - 0s 24ms/step
Current weight: 0.3, Total value: 173.89999999999998
1/1 [==============================] - 0s 24ms/step
Current weight: 0.8, Total value: 526.4
1/1 [==============================] - 0s 34ms/step
Current weight: 0.8, Total value: 526.4
1/1 [==============================] - 0s 27ms/step
Current weight: 0.8, Total value: 526.4
1/1 [==============================] - 0s 24ms/step
Current weight: 4.7, Total value: 907.0999999999999
1/1 [==============================] - 0s 25ms/step
Current weight: 5.0, Total value: 1261.3999999999999
1/1 [==============================] - 0s 25ms/step
Current weight: 5.0, Total value: 1261.3999999999999
1/1 [==============================] - 0s 25ms/step
Current weight: 5.7, Total value: 1408.8999